export const users = [
	{
		"_id": "65cfebc3eb4d91b4acff3f27",
		"index": 0,
		"guid": "3f23bd30-c2b6-475b-9355-40a88109c987",
		"isActive": true,
		"balance": "$1,504.62",
		"picture": "http://placehold.it/32x32",
		"age": 33,
		"eyeColor": "blue",
		"name": "Pitts Sharp",
		"gender": "male",
		"company": "LYRIA",
		"email": "pittssharp@lyria.com",
		"phone": "+1 (910) 514-3465",
		"address": "739 Hillel Place, Calvary, Palau, 2336",
		"about": "Sunt mollit aute in labore duis velit magna. Cupidatat esse consectetur excepteur nisi excepteur occaecat commodo aliqua. Ad fugiat voluptate consequat fugiat labore minim deserunt ullamco. Est ex velit officia mollit do cillum ipsum esse culpa ex veniam. Do excepteur minim exercitation est excepteur voluptate aliqua fugiat aute excepteur. Ut non excepteur qui amet dolor voluptate voluptate voluptate. Anim laborum amet fugiat proident nisi est voluptate ad sunt.\r\n"
	},
	{
		"_id": "65cfebc348ea526d68768c57",
		"index": 1,
		"guid": "a71d8eaa-bd77-42e1-b515-9a2b69970245",
		"isActive": false,
		"balance": "$1,355.79",
		"picture": "http://placehold.it/32x32",
		"age": 28,
		"eyeColor": "green",
		"name": "Alissa Clarke",
		"gender": "female",
		"company": "SOLAREN",
		"email": "alissaclarke@solaren.com",
		"phone": "+1 (877) 431-2687",
		"address": "607 Kossuth Place, Driftwood, Missouri, 9543",
		"about": "Consectetur eiusmod adipisicing ex ullamco nisi adipisicing aliqua sint. Ex pariatur veniam quis consequat eiusmod non veniam elit qui cillum nisi cillum sint voluptate. Anim cupidatat commodo elit anim sint ad nostrud veniam excepteur excepteur consectetur amet fugiat. Occaecat aliqua mollit nisi aliquip ullamco. Laboris proident est sit elit ullamco exercitation irure laboris fugiat consequat fugiat.\r\n"
	},
	{
		"_id": "65cfebc3f5af747b69bb9fb6",
		"index": 2,
		"guid": "91a57281-53b3-4742-a781-f326a0b4d369",
		"isActive": true,
		"balance": "$2,957.82",
		"picture": "http://placehold.it/32x32",
		"age": 33,
		"eyeColor": "green",
		"name": "Galloway Thompson",
		"gender": "male",
		"company": "INRT",
		"email": "gallowaythompson@inrt.com",
		"phone": "+1 (987) 485-2069",
		"address": "255 Lake Avenue, Henrietta, Michigan, 5121",
		"about": "Aliquip laborum esse laboris in est. Labore culpa incididunt anim occaecat Lorem duis est deserunt. Sint in anim sint excepteur esse proident. Amet aliquip esse nulla duis mollit nostrud. Ex proident consectetur proident anim amet do ea officia dolor quis laborum.\r\n"
	},
	{
		"_id": "65cfebc3564925192fa9b953",
		"index": 3,
		"guid": "00a34b11-be0a-48a4-a718-43f3121b8e87",
		"isActive": true,
		"balance": "$3,810.46",
		"picture": "http://placehold.it/32x32",
		"age": 34,
		"eyeColor": "green",
		"name": "Ada Harris",
		"gender": "female",
		"company": "UNCORP",
		"email": "adaharris@uncorp.com",
		"phone": "+1 (960) 577-2680",
		"address": "995 Seigel Street, Alleghenyville, Kentucky, 7176",
		"about": "Deserunt mollit culpa est eu magna. Qui enim ullamco nulla qui veniam. Deserunt minim adipisicing qui proident sit laborum ut aute duis.\r\n"
	},
	{
		"_id": "65cfebc35fdd8660edec3f65",
		"index": 4,
		"guid": "875d7b6f-0909-4811-8f1f-677617bb5818",
		"isActive": false,
		"balance": "$1,822.53",
		"picture": "http://placehold.it/32x32",
		"age": 22,
		"eyeColor": "blue",
		"name": "Serena Cobb",
		"gender": "female",
		"company": "UNISURE",
		"email": "serenacobb@unisure.com",
		"phone": "+1 (851) 447-3274",
		"address": "432 Bushwick Place, Thomasville, Alaska, 333",
		"about": "Veniam proident ea nostrud mollit occaecat Lorem laborum in. Eu laborum occaecat ullamco dolor fugiat excepteur nisi proident. Ipsum eu veniam excepteur ad eu ut deserunt in.\r\n"
	},
	{
		"_id": "65cfebc306519081f6a4e842",
		"index": 5,
		"guid": "934047e2-9204-4e2f-b2ab-320e04a52c91",
		"isActive": true,
		"balance": "$3,244.07",
		"picture": "http://placehold.it/32x32",
		"age": 22,
		"eyeColor": "brown",
		"name": "Frye Puckett",
		"gender": "male",
		"company": "SUNCLIPSE",
		"email": "fryepuckett@sunclipse.com",
		"phone": "+1 (843) 443-2933",
		"address": "805 Lancaster Avenue, Rosine, Mississippi, 2382",
		"about": "Est ex ea est ea tempor Lorem dolore deserunt sunt est qui sunt. Veniam do consectetur tempor mollit dolore ex tempor sint. Deserunt laborum incididunt aute duis occaecat amet ea quis. Excepteur quis consectetur consectetur culpa occaecat nisi labore aliqua adipisicing laboris occaecat ullamco. Nostrud anim veniam cupidatat sint et exercitation ea amet. Cupidatat commodo ullamco non quis ut culpa ullamco laborum nulla aute tempor elit.\r\n"
	}
]